org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
neo_version_range=[21.1.219,)
loader_version_range=[1,)

mod_id=tradetweaks
mod_name=Trade Tweaks
mod_license=Attribution-NonCommercial-ShareAlike 3.0 Unported
mod_version=1.21.1-1.1.0
mod_group_id=net.lostpatrol.tradetweaks
mod_authors=LostPatrol_3
mod_description=Powerful tools and commands for better villager trading experience.
